"""link alerts to incidents

Revision ID: 2f12ad248ffc
Revises: 013281217f77
Create Date: 2026-08-02 20:36:39.899062

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f12ad248ffc"
down_revision: str | Sequence[str] | None = "013281217f77"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alerts", sa.Column("incident_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "alerts", "incidents", ["incident_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "alerts", type_="foreignkey")
    op.drop_column("alerts", "incident_id")
    # ### end Alembic commands ###
